### ISSUE TITLE
resource name option

### ISSUE THREAD

**Issue by driller23** [hsingh/ansible-elastic-beanstalk#10] opened 2016-02-28 19:52 UTC
Hi,

im trying to add the ability of resource name on needed namespace such as the autoscaling trigger.

do you know if the current module can handle that? how?
is boto 2 which is used here has the ability for that?

Igal

**Comment by atward** [comment] 2016-04-21 04:49
Dupe of #9

**Closed as completed** 2016-05-25 16:30 UTC
